version: "3.4"

services:
  app:
    build: .
    restart: always
    depends_on:
      - db
    env_file: .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    expose:
      - ${APP_PORT}
    networks:
      - carbon
    volumes:
      - $PWD:$PWD
  db:
    image: postgres:10.6-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - carbon
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

networks:
  carbon:
    external: true
